//
//  MapLocation.swift
//  SportLocator
//
//  Created by Robert Zinyatullin on 08.03.2023.
//

import MapKit

class MapLocation: NSObject, MKAnnotation {
    var title: String?
    let locationName: String?
    var workingHours: (String, String)?
    var phone: String?
    var webSite: String?
    var image: UIImage?
    var info: String?
    let coordinate: CLLocationCoordinate2D
    let sportType: Sports
    
    init(
        title: String?,
        locationName: String?,
        workingHours: (String, String)?,
        phone: String?,
        webSite: String?,
        image: UIImage?,
        info: String?,
        coordinate: CLLocationCoordinate2D,
        sportType: Sports
    ) {
        self.title = title
        self.locationName = locationName
        self.workingHours = workingHours
        self.phone = phone
        self.webSite = webSite
        self.image = image
        self.info = info
        self.coordinate = coordinate
        self.sportType = sportType
        super.init()
    }
    
    var subtitle: String? {
        return locationName
    }
    
    static let kazanFootballMapAnnotations = [
        MapLocation(title: "Центральный стадион", locationName: "улица Ташаяк, 2а", workingHours: ("08:00", "18:00"), phone: "+7 (843) 292‒58‒46", webSite: "https://www.rubin-kazan.ru/", image: UIImage(named: "football1"), info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ", coordinate: CLLocationCoordinate2D(latitude: 55.796800, longitude: 49.099331), sportType: .football),
        MapLocation(title: "Динамо", locationName: "улица Горького, 10а", workingHours: ("08:00", "22:00"), phone: "+7 (843) 291-35-25", webSite: "http://dinamo.tatarstan.ru/", image: UIImage(named: "football2"), info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ", coordinate: CLLocationCoordinate2D(latitude: 55.792755, longitude: 49.129926), sportType: .football),
        MapLocation(title: "Трудовые резервы", locationName: "улица Николая Ершова, 7", workingHours: ("07:00", "18:00"), phone: "+7 (843) 236‒31‒63", webSite: "https://www.kazan-tr.ru", image: UIImage(named: "football3"), info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ", coordinate: CLLocationCoordinate2D(latitude: 55.795856, longitude: 49.153653), sportType: .football),
        MapLocation(title: "Олимп", locationName: "улица Чистопольская, 65", workingHours: ("08:00", "18:00"), phone: "+7 (843) 562‒03‒85", webSite: "http://kaiolimp.ucoz.ru", image: UIImage(named: "football4"), info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ", coordinate: CLLocationCoordinate2D(latitude: 55.82027586071845, longitude: 49.139435928594054), sportType: .football),
        MapLocation(title: "Ак Барс Арена", locationName: "проспект Ямашева, 115а", workingHours: ("10:00", "19:00"), phone: "+7 (843) 245‒20‒02", webSite: "http://www.akbarsarena.com/", image: UIImage(named: "football5"), info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ", coordinate: CLLocationCoordinate2D(latitude: 55.82082718991573, longitude: 49.16082664094997), sportType: .football),
        MapLocation(title: "Футбольное поле", locationName: "улица Бутлерова, 54А", workingHours: ("00:00", "24:00"), phone: nil, webSite: nil, image: UIImage(named: "football6"), info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ", coordinate: CLLocationCoordinate2D(latitude: 55.7897618, longitude: 49.1398216), sportType: .football),
        MapLocation(title: "Sport City", locationName: "улица Аграрная, д 3", workingHours: ("08:00", "22:00"), phone: "+7 (987) 225‒06‒65", webSite: "http://sportcity-arena.ru", image: UIImage(named: "football7"), info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ", coordinate: CLLocationCoordinate2D(latitude: 55.7930229, longitude: 49.2029444), sportType: .football),
        MapLocation(title: "Водник", locationName: "улица ​Портовая, 2/1", workingHours: ("08:00", "17:00"), phone: nil, webSite: nil, image: UIImage(named: "football8"), info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ", coordinate: CLLocationCoordinate2D(latitude: 55.7724304, longitude: 49.0964614), sportType: .football),
        MapLocation(title: "Электрон", locationName: "улица Карима Тинчурина, 27а", workingHours: ("09:00", "17:00"), phone: "+7 (843) 237‒52‒39", webSite: nil, image: UIImage(named: "football9"), info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ", coordinate: CLLocationCoordinate2D(latitude: 55.7725846, longitude: 49.1096793), sportType: .football),
        MapLocation(title: "Искандер", locationName: "​улица Маршала Чуйкова, 8а", workingHours: ("08:00", "24:00"), phone: "+7 (843) 590‒27‒11", webSite: nil, image: UIImage(named: "football10"), info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ", coordinate: CLLocationCoordinate2D(latitude: 55.8344708, longitude: 49.10815556), sportType: .football)
    ]
    
    static let kazanBasketballMapAnnotations = [
        MapLocation(title: "Урам", locationName: "улица Подлужная, 67б", workingHours: ("09:00", "22:00"), phone: "+7 (843) 222-97-79", webSite: "https://urampark.ru/main", image: UIImage(named: "basketball1"), info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ", coordinate: CLLocationCoordinate2D(latitude: 55.805023, longitude: 49.146269), sportType: .basketball),
        MapLocation(title: "Дан", locationName: "улица Серова, 4а к2", workingHours: ("09:00", "19:00"), phone: "+7 (996) 909‒38‒13", webSite: "https://skdan.ru", image: UIImage(named: "basketball2"), info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ", coordinate: CLLocationCoordinate2D(latitude: 55.82871081934139, longitude: 49.060617127438306), sportType: .basketball),
        MapLocation(title: "Баскет-холл", locationName: "улица Спартаковская, 1", workingHours: ("09:00", "19:00"), phone: "+7 (843) 291-15-00", webSite: "http://www.unics.ru/", image: UIImage(named: "basketball3"), info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ", coordinate: CLLocationCoordinate2D(latitude: 55.782520088356584, longitude: 49.12681070623834), sportType: .basketball),
        MapLocation(title: "Maximus", locationName: "улица Галимджана Баруди, 8", workingHours: ("06:30", "24:00"), phone: "+7 (843) 233‒49‒97", webSite: "https://fcmaximus.ru", image: UIImage(named: "basketball4"), info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ", coordinate: CLLocationCoordinate2D(latitude: 55.820015391677394, longitude: 49.06634954093038), sportType: .basketball),
        MapLocation(title: "Basket Kids School", locationName: "улица 8 Марта, 10", workingHours: ("10:30", "20:00"), phone: "+7 (904) 676‒36‒59", webSite: nil, image: UIImage(named: "basketball5"), info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ", coordinate: CLLocationCoordinate2D(latitude: 55.81182455413298, longitude: 49.18333626976607), sportType: .basketball),
        MapLocation(title: "Xfit АК Барс", locationName: "улица Фатыха Амирхана, 1г", workingHours: ("07:00", "23:00"), phone: "+7 (843) 558-72-67", webSite: "https://akbars.xfit.ru", image: UIImage(named: "basketball6"), info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ", coordinate: CLLocationCoordinate2D(latitude: 55.8117630, longitude: 49.1362780), sportType: .basketball),
        MapLocation(title: "Акимбо", locationName: "улица Юлиуса Фучика, 90", workingHours: ("07:00", "24:00"), phone: "+7 (843) 526-11-26", webSite: "https://akimbofit.ru", image: UIImage(named: "basketball7"), info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ", coordinate: CLLocationCoordinate2D(latitude: 55.7634760, longitude: 49.2334761), sportType: .basketball),
        MapLocation(title: "Алгоритм", locationName: "улица Центральная, 39", workingHours: ("07:00", "22:00"), phone: "+7 (843) 558-58-84", webSite: "http://algoritm-fitnes.ru", image: UIImage(named: "basketball8"), info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ", coordinate: CLLocationCoordinate2D(latitude: 55.7669557, longitude: 49.2553390), sportType: .basketball),
        MapLocation(title: "Академия тенниса Ш. Тарпищева", locationName: "улица Урицкого, 17", workingHours: ("07:00", "23:00"), phone: "+7 (843) 210-16-50", webSite: "https://tennisacadem.ru", image: UIImage(named: "basketball9"), info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ", coordinate: CLLocationCoordinate2D(latitude: 55.8001606, longitude: 49.0585602), sportType: .basketball),
        MapLocation(title: "Диана", locationName: "улица Рихарда Зорге, 60", workingHours: ("08:00", "22:00"), phone: "+7 (843) 224-18-83", webSite: nil, image: UIImage(named: "basketball10"), info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ", coordinate: CLLocationCoordinate2D(latitude: 55.7527168, longitude: 49.2023635), sportType: .basketball)
    ]
    
    static let kazanVolleyballMapAnnotations = [
        MapLocation(title: "Центр пляжного волейбола", locationName: "​улица Сибгата Хакима, 62а", workingHours: ("08:00", "22:00"), phone: "+7 (843) 245-65-20", webSite: "https://sportplyazh.ru", image: UIImage(named: "volleyball1"), info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ", coordinate: CLLocationCoordinate2D(latitude: 55.81492375763865, longitude: 49.147205088496456), sportType: .volleyball),
        MapLocation(title: "VolleyandYou", locationName: "​улица Односторонка Гривки, 1в", workingHours: ("08:00", "24:00"), phone: "+7 (843) 717‒95‒92", webSite: "https://volley-kazan.ru", image: UIImage(named: "volleyball2"), info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ", coordinate: CLLocationCoordinate2D(latitude: 55.81271409413791, longitude: 49.09480224093011), sportType: .volleyball),
        MapLocation(title: "VolleyandYou", locationName: "​улица Тверская, 2а", workingHours: ("08:00", "24:00"), phone: "+7 (843) 717‒95‒92", webSite: "https://volley-kazan.ru", image: UIImage(named: "volleyball3"), info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ", coordinate: CLLocationCoordinate2D(latitude: 55.82591135147814, longitude: 49.08225445627417), sportType: .volleyball),
        MapLocation(title: "Планета Фитнес", locationName: "​​улица Хади Такташа, 24", workingHours: ("06:30", "23:00"), phone: "+7 (843) 207‒02‒81", webSite: "https://planeta.fitness", image: UIImage(named: "volleyball4"), info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ", coordinate: CLLocationCoordinate2D(latitude: 55.779704000113824, longitude: 49.1263496256894), sportType: .volleyball),
        MapLocation(title: "VolleyandYou", locationName: "​улица Даурская, 16д", workingHours: ("08:00", "22:00"), phone: "+7 (843) 717‒95‒92", webSite: "https://volley-kazan.ru", image: UIImage(named: "volleyball5"), info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ", coordinate: CLLocationCoordinate2D(latitude: 55.76157842740225, longitude: 49.14868687161549), sportType: .volleyball),
        MapLocation(title: "Центр волейбола", locationName: "​улица Мидхата Булатова, 1", workingHours: ("09:00", "18:00"), phone: "+7 (843) 221‒83‒01", webSite: "https://dinamo-kazan.com/about/arena/", image: UIImage(named: "volleyball6"), info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ", coordinate: CLLocationCoordinate2D(latitude: 55.7335898, longitude: 49.1719798), sportType: .volleyball),
        MapLocation(title: "Ак Буре", locationName: "​улица Односторонка Гривки, 1в", workingHours: ("08:00", "22:00"), phone: "+7 (843) 276‒33‒10", webSite: nil, image: UIImage(named: "volleyball7"), info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ", coordinate: CLLocationCoordinate2D(latitude: 55.7833550, longitude: 49.2296740), sportType: .volleyball),
        MapLocation(title: "Физ-Ра", locationName: "​улица Сары Садыковой, 30", workingHours: ("08:00", "22:00"), phone: "+7 (843) 212‒22‒33", webSite: "https://fizra.fit", image: UIImage(named: "volleyball8"), info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ", coordinate: CLLocationCoordinate2D(latitude: 55.7738368, longitude: 49.1160384), sportType: .volleyball),
        MapLocation(title: "Тулпар", locationName: "​​улица Рауиса Гареева, 80", workingHours: ("08:00", "20:00"), phone: "+7 (843) 221‒31‒03", webSite: nil, image: UIImage(named: "volleyball9"), info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ", coordinate: CLLocationCoordinate2D(latitude: 55.7197664, longitude: 49.1686192), sportType: .volleyball),
        MapLocation(title: "Тэзуче", locationName: "​улица Зеленая, 2а", workingHours: ("08:00", "18:00"), phone: "+7 (843) 236‒25‒81", webSite: nil, image: UIImage(named: "volleyball10"), info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ", coordinate: CLLocationCoordinate2D(latitude: 55.7833532, longitude: 49.1410449), sportType: .volleyball)
        
    ]
    
    static let kazanHockeyMapAnnotations = [
        MapLocation(title: "ТАТНЕФТЬ АРЕНА", locationName: "улица Чистопольская, 42", workingHours: ("09:00", "19:00"), phone: "+7 (843) 527-85-85", webSite: "http://www.tna-tickets.ru/", image: UIImage(named: "hockey1"), info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ", coordinate: CLLocationCoordinate2D(latitude: 55.81769193417374, longitude: 49.124602867355065), sportType: .hockey),
        MapLocation(title: "РСШОР Динамо", locationName: "улица Карима Тинчурина, 27а", workingHours: ("08:00", "23:00"), phone: "+7 (843) 237‒52‒33", webSite: "http://tatrsdinamo.tatar", image: UIImage(named: "hockey2"), info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ", coordinate: CLLocationCoordinate2D(latitude: 55.772986921476395, longitude: 49.109635529554375), sportType: .hockey),
        MapLocation(title: "Ватан", locationName: "улица Чуйкова, д. 8", workingHours: ("09:00", "18:00"), phone: "+7 (843) 562-06-50", webSite: "https://edu.tatar.ru/nsav/about", image: UIImage(named: "hockey3"), info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ", coordinate: CLLocationCoordinate2D(latitude: 55.83329888334207, longitude: 49.1081757660642), sportType: .hockey),
        MapLocation(title: "Триумф", locationName: "улица Олега Кошевого, 17", workingHours: ("09:00", "21:00"), phone: "+7 (843) 562-06-01", webSite: nil, image: UIImage(named: "hockey4"), info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ", coordinate: CLLocationCoordinate2D(latitude: 55.857305699007775, longitude: 49.09328808518984), sportType: .hockey),
        MapLocation(title: "Тасма", locationName: "улица Гагарина, 56", workingHours: ("10:00", "19:00"), phone: "+7 (843) 527-85-85", webSite: "https://edu.tatar.ru/moskow/org5721", image: UIImage(named: "hockey5"), info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ", coordinate: CLLocationCoordinate2D(latitude: 55.83627179538927, longitude: 49.06291313068717), sportType: .hockey),
        
        MapLocation(title: "Баско", locationName: "улица Степана Халтурина, 3", workingHours: ("09:00", "21:00"), phone: "+7 (843) 237‒75‒01", webSite: nil, image: UIImage(named: "hockey6"), info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ", coordinate: CLLocationCoordinate2D(latitude: 55.8149237, longitude: 49.0541233), sportType: .hockey),
        MapLocation(title: "Золотая шайба", locationName: "улица Гаврилова, 48а", workingHours: ("08:00", "20:00"), phone: "+7 (843) 223‒08‒45", webSite: nil, image: UIImage(named: "hockey7"), info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ", coordinate: CLLocationCoordinate2D(latitude: 55.8399857, longitude: 49.1554321), sportType: .hockey),
        MapLocation(title: "Зилант", locationName: "улица Хусаина Мавлютова, 17в", workingHours: ("06:00", "23:00"), phone: "+7 (843) 237‒76‒31", webSite: "https://unifirst-services.ru", image: UIImage(named: "hockey8"), info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ", coordinate: CLLocationCoordinate2D(latitude: 55.7518530, longitude: 49.1914315), sportType: .hockey),
        MapLocation(title: "Форвард", locationName: "улица Химиков, 40", workingHours: ("08:00", "22:00"), phone: "+7 (843) 562‒06‒29", webSite: nil, image: UIImage(named: "hockey9"), info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ", coordinate: CLLocationCoordinate2D(latitude: 55.8748268, longitude: 49.0146309), sportType: .hockey),
        MapLocation(title: "Дворец спорта", locationName: "улица Гагарина, 56", workingHours: ("09:00", "18:00"), phone: "+7 (843) 292‒26‒73", webSite: "https://sportsarae.ru", image: UIImage(named: "hockey10"), info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ", coordinate: CLLocationCoordinate2D(latitude: 55.7940904, longitude: 49.0995803), sportType: .hockey)
    ]
}

class MapLocationView: MKAnnotationView {
    override var annotation: MKAnnotation? {
        willSet {
            guard newValue is MapLocation else {
                return
            }

            image = UIImage(named: "mapLocationLogo")!
        }
    }
}

class UserLocationView: MKAnnotationView {
    override var annotation: MKAnnotation? {
        willSet {
            guard newValue is UserLocationView else {
                return
            }
        }
    }
}
